dist: bionic
language: python

sudo: false

cache:
    apt: true
    pip: true

python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - 3.8-dev
  - nightly
  - pypy3

env:
  - DIST=sdist
    WITH_COVERAGE=1
  - DIST=wheel
    WITH_COVERAGE=0

matrix:
  fast_finish: true
  include:
    - python: 3.8
      env: TOXENV=check
    - python: 3.8
      env:
        - TOXENV=regression
          WITH_COVERAGE=1
      addons:
        apt:
          packages:
            - imagemagick
            - poppler-utils
    - os: osx
      sudo: required
      language: objective-c
      cache:
        pip: false
        directories:
          - /usr/local/Homebrew
          - $HOME/Library/Caches/Homebrew
          - $HOME/Library/Caches/pip
          - $HOME/.pyenv
      env:
        - DIST=sdist
          WITH_COVERAGE=1
        # don't set TOXENV; run all envs listed in tox.ini's envlist
      before_install:
        - brew unlink pyenv
        - brew install --HEAD pyenv
        - brew install --HEAD pyenv-virtualenv
        - eval "$(pyenv init -)"
        - eval "$(pyenv virtualenv-init -)"
        - /usr/bin/python pyenv_setup.py
        - pyenv virtualenv --force 3.8.1 rinoh-tox
        - python --version
        - python3 --version
        - python3.5 --version
        - python3.6 --version
        - python3.7 --version
        - python3.8 --version
        - pip install -r rinoh-tox.txt
      install:
      before_cache:
        - brew cleanup
    - python: 3.8
      env:
        - TOXENV=longrunning
          TIMEOUT=45
          WITH_COVERAGE=0
      addons:
        apt:
          packages:
            - imagemagick
            - poppler-utils
    - python: 3.8
      env: TOXENV=check-docs
    - python: 3.8
      env: TOXENV=build-docs
    - os: osx
      sudo: required
      language: objective-c
      cache:
        pip: false
        directories:
          - /usr/local/Homebrew
          - $HOME/Library/Caches/Homebrew
          - $HOME/Library/Caches/pip
          - $HOME/.pyenv
      env:
        - TOXENV=macapp
      before_install:
        - brew unlink pyenv
        - brew install --HEAD pyenv
        - eval "$(pyenv init -)"
        - pyenv install --skip-existing 3.7.6
        - pyenv shell 3.7.6
        - python --version
      before_cache:
        - brew cleanup

install:
  - pip install tox-travis wheel
  - python setup.py bdist_wheel

script:
  - function timeout { [ -z $TIMEOUT ] || echo "travis_wait $TIMEOUT"; }
  - function installpkg { [[ $DIST == "wheel" ]] && echo "--installpkg ./dist/rinohtype-*.whl"; }
  - $(timeout) tox -v $(installpkg)

after_success:
  - "[[ $WITH_COVERAGE -eq 1 ]] && bash <(curl -s https://codecov.io/bash) -f coverage.xml -F ${TOXENV:-unittests}"

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/cccb04073ce95d678fd3
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
