language: python

sudo: false

cache:
    apt: true
    directories:
      - $HOME/.cache/pip

python:
  - 3.3
  - 3.4
  - 3.5
  - nightly
  - pypy3.3-5.2-alpha1

env:
  - DIST=sdist
    WITH_COVERAGE=1
  - DIST=wheel
    WITH_COVERAGE=0

matrix:
  include:
    - python: 3.5
      env: TOXENV=check
    - python: 3.5
      env:
        - TOXENV=regression
          TIMEOUT=45
          WITH_COVERAGE=1
      addons:
        apt:
          packages:
            - imagemagick
      before_install:
        # install poppler 0.41.0 (required by the diffpdf script)
        - travis_retry curl -L http://brechtm.github.io/rinohtype-travis/dotlocal.tar.xz | tar xJ -C ~
        - export PATH=$HOME/.local/bin:$PATH
        - export LD_LIBRARY_PATH=$HOME/.local/lib
    - python: 3.5
      env: TOXENV=test-docs

install:
  - pip install tox-travis wheel
  - python setup.py bdist_wheel

script:
  - function timeout { [ -z $TIMEOUT ] || echo "travis_wait $TIMEOUT"; }
  - function installpkg { [[ $DIST == "wheel" ]] && echo "--installpkg ./dist/rinohtype-*.whl"; }
  - $(timeout) tox -v $(installpkg)

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/cccb04073ce95d678fd3
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
