# References:
# - https://packaging.python.org/appveyor/
# - https://github.com/cloudify-cosmo/appveyor-utils

# https://www.appveyor.com/docs/how-to/rdp-to-build-worker/
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))


environment:
  matrix:
    # For Python versions available on Appveyor, see
    # http://www.appveyor.com/docs/installed-software#python
#    - PYTHON: "C:\\Python33"
#    - PYTHON: "C:\\Python34"
#    - PYTHON: "C:\\Python35"
#    - PYTHON: "C:\\Python33-x64"
#    - PYTHON: "C:\\Python34-x64"
    - PYTHON: "C:\\Python35-x64"

install:
  - choco install imagemagick.tool
  - set PATH=C:\ProgramData\chocolatey\lib\imagemagick.tool\tools;%PATH%
  - set PATH=C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%
  - bash -lc "pacman --noconfirm --sync --refresh --refresh pacman"
  - bash -lc "pacman --noconfirm --sync --refresh --refresh --sysupgrade --sysupgrade"
  - bash -xlc "pacman --noconfirm -S --needed tar unzip make"
  - bash -xlc "pacman --noconfirm -S --needed mingw-w64-x86_64-poppler"


build: off


before_test:
  - echo %PATH%
  - "%PYTHON%\\python.exe -m pip install tox-travis"

test_script:
  - "%PYTHON%\\python.exe -m tox"
