# References:
# - https://packaging.python.org/appveyor/
# - https://github.com/cloudify-cosmo/appveyor-utils

# https://www.appveyor.com/docs/how-to/rdp-to-build-worker/
#init:
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
#
#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))


environment:
  global:
    BASETEMP: '%APPVEYOR_BUILD_FOLDER%\pytest_temp'

  matrix:
#    - TOXENV: py33,py34,py35,py36
##      DIST: sdist
##      WITH_COVERAGE: 1
##    - TOXENV: py33,py34,py35,py36
##      DIST: wheel
##      WITH_COVERAGE: 0
#    - TOXENV: check
#    - TOXENV: regression
##      WITH_COVERAGE: 1
#    - TOXENV: longrunning
##      WITH_COVERAGE: 0
#    - TOXENV: test-docs
#    - TOXENV: build-docs
    - TOXENV: wininst

cache:
  - C:\poppler-0.51 -> appveyor.yml
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml

install:
  - ps: |
      If ($env:TOXENV -Match "regression" -Or $env:TOXENV -Match "longrunning") {
          If (!(Test-Path C:\poppler-0.51)) {
              # http://blog.alivate.com.au/poppler-windows/
              appveyor DownloadFile http://blog.alivate.com.au/wp-content/uploads/2017/01/poppler-0.51_x86.7z
              7z x poppler-0.51_x86.7z -oC:\
          }
          choco install imagemagick.tool
          $env:Path = "C:\ProgramData\chocolatey\lib\imagemagick.tool\tools;C:\poppler-0.51\bin;$env:Path"
          git submodule update --quiet --init
      }
      If ($env:TOXENV -Match "wininst") {
          choco install html-help-workshop
          $env:Path = "C:\Program Files (x86)\HTML Help Workshop;$env:Path"
      }


build: off


before_test:
  - py -3.5 -m pip install tox-travis

test_script:
  - echo %PATH%
  - py -3.5 -m tox


on_success:
  - ps: |
      If ($env:TOXENV -Match "wininst") {
          Get-ChildItem .\build\nsis\rinoh_*.exe | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
      }

on_failure:
  - ps: |
      If ($env:TOXENV -Match "regression" -Or $env:TOXENV -Match "longrunning") {
          7z a pytest_temp.zip pytest_temp
          Push-AppveyorArtifact pytest_temp.zip
      }
